### ISSUE TITLE
Would you release the checkpoints of ViT-Tiny-21M-384 and TinyViT-21M-512?

### ISSUE THREAD

**Issue by youngfly11** [microsoft/Cream#113]
![image](https://user-images.githubusercontent.com/24568308/183805574-edf364ed-64ef-4867-9521-2ae448ec0c0a.png)

Hi, authors;

Thanks for your excellent work for TinyViT. May I ask whether you are going to release the checkpoints of ViT-Tiny-21M-384/512?

Thanks

**Comment by wkcn** [comment]
Thanks for your attention to our work!

We did not train or finetune the model under high resolution on ImageNet-22k.
The models under high resolution (`TinyViT-21M-384` and `TinyViT-21M-512`) in the paper are both finetuned on ImageNet-1k, where the resume models are `TinyViT-21M-224-22k` and `TinyViT-21M-384`, respectively.

Specifically, we first finetune `TinyViT-21M-384` on IN-1k, then finetune the 384 model to 512 on IN-1k.
