### ISSUE TITLE
AutoFormer: How to set the fine-tuning code for downstream tasks? e.g. Cifar100

### ISSUE THREAD

**Issue by Swiftsss** [microsoft/Cream#115]

**Comment by nbl97** [comment]
Thanks for your interest in our work. To change the input size of  the trained AutoFormer models for downstream tasks, you have several steps to go:

1. We always divide the image into 16x16 small patches. If the input sizes are different, we will have different  numbers of patches. This will affect the position embedding and the classification head. Besides, the classification head is dedicated to ImageNet, so we should remove it from the checkpoint.  

2. Remove the original classification head from the checkpoint.
```
for k in ['head.weight', 'head.bias']:
    if k in checkpoint['model'] and checkpoint['model'][k].shape != state_dict[k].shape:
        print(f"Removing key {k} from pretrained checkpoint")
        del checkpoint['model'][k]
```
3. Interpolate the position embedding as suggested in [DeiT](https://github.com/facebookresearch/deit/blob/8ab59156f435cc7be62791ed2edbc65553fc665f/main.py#L283). 
```
pos_embed = checkpoint['model']['pos_embed']
_, N, C = pos_embed.shape
class_pos_embed = pos_embed[:, 0, :].unsqueeze(1)
old_patch_num = int((N - 1) ** 0.5)
pos_embed = pos_embed.permute(0, 2, 1)[:, :, 1:].reshape(1, -1, old_patch_num, old_patch_num)
interpolate_pos_embed = torch.nn.functional \
    .interpolate(pos_embed, size=(args.input_size // 16, args.input_size // 16), mode='bicubic') \
    .reshape(1, C, -1).permute(0, 2, 1)
interpolate_pos_embed = [torch.cat](http://torch.cat/)([class_pos_embed, interpolate_pos_embed], dim=1)
checkpoint['model']['pos_embed'] = interpolate_pos_embed
```
If you have further questions, please feel free to let us know.

**Comment by Swiftsss** [comment]
Thank you!
