### ISSUE TITLE
Can RTX3090 install iRPE?

### ISSUE THREAD

**Issue by LemonQC** [microsoft/Cream#119]

**Comment by wkcn** [comment]
Thanks for your attention to our work!

Yes, the cuda custom operator of iRPE can be installed on NVIDIA GPUs, including RTX3090.

The custom operator is not necessary, and the latest version of PyTorch may has optimized the speed.

**Comment by LemonQC** [comment]
However, I run with CUDA11.0,pytorch1.7.1. It seems doesn't work.

**Comment by wkcn** [comment]
@LemonQC 
Oh, the issue may be similar to the one #75 .

The reason is that the installed NVCC does not support compute_86.
Could you please try TORCH_CUDA_ARCH_LIST="7.5" python setup.py install --user to build the custom operator ?

**Comment by LemonQC** [comment]
@wkcn Many Thanks. it works.
