### ISSUE TITLE
A strange error

### ISSUE THREAD

**Issue by December-boy** [microsoft/Cream#12]
![1f197c3228ebfa55b8ff3f446e2791d](https://user-images.githubusercontent.com/23350028/103524124-f87f3500-4eb7-11eb-82dc-56f308f54fb3.png)
"techer_cand is None", anyone have ideas?

**Comment by Z7zuqer** [comment]
Hi,

Could you provide more infomation about training log?

Best,
Hao.

**Comment by December-boy** [comment]
One more thing, in the early stage of train, the accurates of the saved checkpoints are in a low level, is that a normal case?

12/11 04:39:17 PM | Train: 33 [5000/5004 (100%)]  Loss:  5.606739 (5.8622)  KD-Loss:  5.868071 (5.9112)  Prec@1:  7.0312 ( 6.8421)  Prec@5: 20.7031 (18.9889)  Time: 3.053s,   83.86/s  (0.678s,  377.36/s)  LR: 3.583e-01  Data: 0.006 (0.008)
12/11 04:39:20 PM | Train: 33 [5003/5004 (100%)]  Loss:  5.950589 (5.8622)  KD-Loss:  5.796462 (5.9112)  Prec@1:  5.4688 ( 6.8415)  Prec@5: 18.7500 (18.9882)  Time: 1.224s,  209.09/s  (0.679s,  377.30/s)  LR: 3.583e-01  Data: 0.613 (0.008)
12/11 04:39:20 PM | No.0 (tensor(14.8438, device='cuda:0'), tensor(14.8438, device='cuda:0'), 421.330992, [[0], [2, 0, 3, 2], [2, 3, 1, 2], [2, 5, 3, 3], [3, 3, 1, 5], [4, 0, 5, 3], [0]])
12/11 04:39:20 PM | No.1 (tensor(14.8438, device='cuda:0'), tensor(14.8438, device='cuda:0'), 378.956912, [[0], [4, 2, 2, 0], [2, 2, 4, 5], [0, 4, 4, 4], [5, 0, 0, 0], [0, 1, 3, 1], [0]])
12/11 04:39:20 PM | No.2 (tensor(14.0625, device='cuda:0'), tensor(14.0625, device='cuda:0'), 488.8528000000001, [[0], [4, 3, 5, 4], [1, 4, 5, 4], [5, 3, 3, 2], [3, 5, 5, 5], [3, 1, 5, 1], [0]])
12/11 04:39:20 PM | No.3 (tensor(14.0625, device='cuda:0'), tensor(14.0625, device='cuda:0'), 423.6392639999999, [[0], [0, 1, 5, 4], [2, 1, 4, 3], [3, 4, 1, 4], [3, 3, 0, 4], [0, 4, 3, 5], [0]])
12/11 04:39:20 PM | No.4 (tensor(13.6719, device='cuda:0'), tensor(13.6719, device='cuda:0'), 394.42361600000004, [[0], [4, 5, 4, 2], [4, 0, 2, 0], [5, 3, 4, 0], [2, 5, 1, 2], [4, 0, 2, 0], [0]])
12/11 04:39:20 PM | No.5 (tensor(13.2812, device='cuda:0'), tensor(13.2812, device='cuda:0'), 393.9822399999999, [[0], [4, 3, 4, 0], [2, 2, 3, 3], [1, 5, 1, 4], [1, 0, 0, 0], [4, 0, 4, 3], [0]])
12/11 04:39:20 PM | No.6 (tensor(13.2812, device='cuda:0'), tensor(13.2812, device='cuda:0'), 392.60233600000004, [[0], [0, 2, 0, 1], [2, 4, 3, 3], [3, 3, 2, 2], [2, 0, 3, 4], [0, 5, 3, 5], [0]])
12/11 04:39:20 PM | No.7 (tensor(13.2812, device='cuda:0'), tensor(13.2812, device='cuda:0'), 379.4572799999999, [[0], [1, 4, 0, 0], [2, 1, 2, 0], [2, 1, 2, 3], [5, 5, 1, 4], [4, 2, 2, 2], [0]])
12/11 04:39:20 PM | No.8 (tensor(13.2812, device='cuda:0'), tensor(13.2812, device='cuda:0'), 376.7034719999999, [[0], [2, 1, 0, 0], [5, 4, 4, 0], [4, 4, 5, 1], [1, 0, 2, 3], [5, 2, 4, 4], [0]])
12/11 04:39:20 PM | No.9 (tensor(12.8906, device='cuda:0'), tensor(12.8906, device='cuda:0'), 377.18105599999996, [[0], [2, 2, 3, 2], [4, 0, 0, 1], [2, 5, 4, 2], [2, 0, 1, 1], [4, 4, 0, 3], [0]])
12/11 04:40:01 PM | Test: [   0/48]  Time: 41.177 (41.177)  Loss:  4.8947 (4.8947)  Prec@1:  9.7656 ( 9.7656)  Prec@5: 30.9570 (30.9570)
12/11 04:40:46 PM | Test: [  48/48]  Time: 0.629 (1.759)  Loss:  5.3491 (5.5790)  Prec@1: 11.6745 ( 6.1620)  Prec@5: 23.5849 (18.6620)
12/11 04:40:49 PM | Current checkpoints:
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-13.pth.tar', 8.313999998168946)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-18.pth.tar', 6.470000031738281)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-23.pth.tar', 6.45800000579834)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-33.pth.tar', 6.162000013122559)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-14.pth.tar', 5.926000026855469)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-21.pth.tar', 5.555999999084473)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-26.pth.tar', 5.366000014648438)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-28.pth.tar', 5.099999999084472)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-30.pth.tar', 5.03199999206543)
 ('./experiments/workspace/train/1210-Supernet_Training/checkpoint-17.pth.tar', 4.934000001220703)

**Comment by Z7zuqer** [comment]
Have you changed the learning parameters?

If the meta_value generated by the metaNN is NaN, this could occur.

Best,
Hao.

**Comment by December-boy** [comment]
> Have you changed the learning parameters?
> 
> If the meta_value generated by the metaNN is NaN, this could occur.
> 
> Best,
> Hao.
This is the configs:
AUTO_RESUME: False
DATA_DIR: '/home/seeta-uihyvk/nfs/zqq/pt.darts-master/experiments/data/imagenet/'
MODEL: 'Supernet_Training'
RESUME_PATH: './experiments/workspace/train/resume.pth.tar'
SAVE_PATH: './experiments/workspace/train'
SEED: 42
LOG_INTERVAL: 500
RECOVERY_INTERVAL: 0
WORKERS: 6
NUM_GPU: 4
SAVE_IMAGES: False
AMP: False
OUTPUT: 'None'
EVAL_METRICS: 'prec1'
TTA: 0
LOCAL_RANK: 0

DATASET:
  NUM_CLASSES: 1000
  IMAGE_SIZE: 224 # image patch size
  INTERPOLATION: 'bilinear' # Image resize interpolation type
  BATCH_SIZE: 64 # batch size

NET:
  GP: 'avg'
  DROPOUT_RATE: 0.0

  EMA:
    USE: True
    FORCE_CPU: False # force model ema to be tracked on CPU
    DECAY: 0.9998

OPT: 'sgd'
LR: 1.0
EPOCHS: 120
META_LR: 1e-4

BATCHNORM:
  SYNC_BN: False

SUPERNET:
  UPDATE_ITER: 200
  SLICE: 4
  POOL_SIZE: 10
  RESUNIT: False
  DIL_CONV: False
  UPDATE_2ND: True
  FLOPS_MINIMUM: 0
  FLOPS_MAXIMUM: 600
  PICK_METHOD: 'meta'
  META_STA_EPOCH: 20
  HOW_TO_PROB: 'pre_prob'
  PRE_PROB: (0.05,0.2,0.05,0.5,0.05,0.15)

**Comment by Z7zuqer** [comment]
It seems due to the changes of batchsize, the corresponding hyperparameters should be changed too.

You could check the value of meta_value and the updates of metaNN, make sure that metaNN runs normally.

**Comment by December-boy** [comment]
> It seems due to the changes of batchsize, the corresponding hyperparameters should be changed too.
> 
> You could check the value of meta_value and the updates of metaNN, make sure that metaNN runs normally.

the batchsize is changed from 128 to 64, Do I need to halve the learning rate？

**Comment by December-boy** [comment]
> Hi,
> 
> Could you provide more infomation about training log?
> 
> Best,
> Hao.

R: 3.269e-01 Data: 0.005 (0.009)
12/27 10:01:28 PM | Train: 41 [2650/5004 { 53%)] Loss: 16.545618 (6.2345) KD-Loss: 5.539803 (6.1587) Prec@l: 0.0000 { 3.8587) Prec@5: 0.0000 (12.4776) Time: 0.659s, 388.73/s (0.659s, 388.52/s) L
R: 3.269e-01 Data: 0.005 (0.009)
Traceback (most recent call last):
File ■tools/train.py", line 239, in <module> 
main()
File ■tools/train.py", line 217, in main 
est=model_est, locai._rank=args .T.ocal._rank)
File ■/home//Cream/tools/../lib/core/t rain.py-, line 47, in train_epoch 
meta_value, teacher_cand = prioritized_board.sel.ect_teacher(model, random_cand)
File ■/home//Cream/tools/../T-ib/models/PrioritizedBoard.py", line 37, in select_teacher 
assert teacher_cand is not None 
AssertionError
Traceback (most recent call last):
File ■tools/train.py", line 239, in <module> 
main()
File ■tools/train.py", line 217, in main 
est=model_est, locai._rank=args .T.ocal._rank)
File ■/home//Cream/tools/../lib/core/train.py-, line 47, in train_epoch 
meta_value, teacher_cand = prioritized_board.sel.ect_teacher(model, random_cand)
File B/home//Cream/tools/../T-ib/models/PrioritizedBoard.py", line 37, in select_teacher 
assert teacher_cand is not None 
AssertionError
Traceback (most recent call last):
File ■tools/train.py", line 239, in <module> 
main()
File ■tools/train.py", line 217, in main 
est=model_est, locai._rank=args .T.ocal._rank)
File ■/home//Cream/tools/../lib/core/train.py-, line 47, in train_epoch 
meta_value, teacher_cand = prioritized_board.sel.ect_teacher(model, random_cand)
File B/home//Cream/tools/../T-ib/models/PrioritizedBoard.py", line 37, in select_teacher 
assert teacher_cand is not None 
AssertionError

**Comment by Z7zuqer** [comment]
Hi,

It seems that your batchsize(64*4) is far less than ours(128*8).

You could try to downsize the learning rate, e.g., meta_lr/4, meta_lr/(2*2^(1/2)), lr/4.....

Please make sure the gradients are normal value instead of NaN.

Best,
Hao.

**Comment by December-boy** [comment]
> > Hi,
> > Could you provide more infomation about training log?
> > Best,
> > Hao.
> 
> R: 3.269e-01 Data: 0.005 (0.009)
> 12/27 10:01:28 PM | Train: 41 [2650/5004 { 53%)] Loss: 16.545618 (6.2345) KD-Loss: 5.539803 (6.1587) Prec@l: 0.0000 { 3.8587) Prec@5: 0.0000 (12.4776) Time: 0.659s, 388.73/s (0.659s, 388.52/s) L
> R: 3.269e-01 Data: 0.005 (0.009)
> Traceback (most recent call last):
> File ■tools/train.py", line 239, in
> main()
> File ■tools/train.py", line 217, in main
> est=model_est, locai._rank=args .T.ocal._rank)
> File ■/home//Cream/tools/../lib/core/t rain.py-, line 47, in train_epoch
> meta_value, teacher_cand = prioritized_board.sel.ect_teacher(model, random_cand)
> File ■/home//Cream/tools/../T-ib/models/PrioritizedBoard.py", line 37, in select_teacher
> assert teacher_cand is not None
> AssertionError
> Traceback (most recent call last):
> File ■tools/train.py", line 239, in
> main()
> File ■tools/train.py", line 217, in main
> est=model_est, locai._rank=args .T.ocal._rank)
> File ■/home//Cream/tools/../lib/core/train.py-, line 47, in train_epoch
> meta_value, teacher_cand = prioritized_board.sel.ect_teacher(model, random_cand)
> File B/home//Cream/tools/../T-ib/models/PrioritizedBoard.py", line 37, in select_teacher
> assert teacher_cand is not None
> AssertionError
> Traceback (most recent call last):
> File ■tools/train.py", line 239, in
> main()
> File ■tools/train.py", line 217, in main
> est=model_est, locai._rank=args .T.ocal._rank)
> File ■/home//Cream/tools/../lib/core/train.py-, line 47, in train_epoch
> meta_value, teacher_cand = prioritized_board.sel.ect_teacher(model, random_cand)
> File B/home//Cream/tools/../T-ib/models/PrioritizedBoard.py", line 37, in select_teacher
> assert teacher_cand is not None
> AssertionError

This error occurred in different epochs:
```
01/04 07:35:43 PM | Train: 36 [3500/5004 ( 70%)]  Loss:  6.273274 (6.0771)  KD-Loss:  6.230510 (6.0881)  Prec@1:  5.0781 ( 5.1771)  Prec@5: 14.0625 (15.4503)  Time: 0.677s,  378.30/s  (0.649s,  394.36/s)  LR: 3.470e-01  Data: 0.005 (0.007)
01/04 07:41:11 PM | Train: 36 [4000/5004 ( 80%)]  Loss:  7.453385 (6.0772)  KD-Loss:  4.069088 (6.0934)  Prec@1:  3.1250 ( 5.1671)  Prec@5: 11.3281 (15.4072)  Time: 2.884s,   88.76/s  (0.650s,  393.92/s)  LR: 3.466e-01  Data: 0.005 (0.007)
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main()
  File "tools/train.py", line 217, in main
    est=model_est, local_rank=args.local_rank)
  File "/home/Cream/tools/../lib/core/train.py", line 47, in train_epoch
    meta_value, teacher_cand = prioritized_board.select_teacher(model, random_cand)
  File "/home/Cream/tools/../lib/models/PrioritizedBoard.py", line 37, in select_teacher
    assert teacher_cand is not None
AssertionError
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main()
  File "tools/train.py", line 217, in main
    est=model_est, local_rank=args.local_rank)
  File "/home/Cream/tools/../lib/core/train.py", line 47, in train_epoch
    meta_value, teacher_cand = prioritized_board.select_teacher(model, random_cand)
  File "/home/Cream/tools/../lib/models/PrioritizedBoard.py", line 37, in select_teacher
    assert teacher_cand is not None
AssertionError
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main()
  File "tools/train.py", line 217, in main
    est=model_est, local_rank=args.local_rank)
  File "/home/Cream/tools/../lib/core/train.py", line 47, in train_epoch
    meta_value, teacher_cand = prioritized_board.select_teacher(model, random_cand)
  File "/home/Cream/tools/../lib/models/PrioritizedBoard.py", line 37, in select_teacher
    assert teacher_cand is not None
AssertionError
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main()
  File "tools/train.py", line 217, in main
    est=model_est, local_rank=args.local_rank)
  File "/home/Cream/tools/../lib/core/train.py", line 47, in train_epoch
    meta_value, teacher_cand = prioritized_board.select_teacher(model, random_cand)
  File "/home/Cream/tools/../lib/models/PrioritizedBoard.py", line 37, in select_teacher
    assert teacher_cand is not None
AssertionError
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/bin/python', '-u', 'tools/train.py', '--local_rank=3', '--cfg', './experiments/configs/train/train.yaml']' returned non-zero exit status 1.

```

**Comment by December-boy** [comment]
> Hi,
> 
> It seems that your batchsize(64x4) is far less than ours(128x8).
> 
> You could try to downsize the learning rate, e.g., meta_lr/4, meta_lr/(2*2^(1/2)), lr/4.....
> 
> Please make sure the gradients are normal value instead of NaN.
> 
> Best,
> Hao.

many thanks, I'll have a try.

**Comment by Z7zuqer** [comment]
> Hi, I tried to use larger batch size 64x8 and reduce meta_lr, but this assertion (assert teacher_cand is not None) still happens.
> It always shows up at epoch 22.

Hi,

our origin batchsize is 8*128(larger than 64*8), the cause of this error is the same as the above. You have to adjust the learning rate of meta module to make sure the correctness of gradients.

Best,
Hao.
