### ISSUE TITLE
Question about the Conv_BN in TinyViT

### ISSUE THREAD

**Issue by tonysy** [microsoft/Cream#123]
Hi,
I find the tinyvit uses Conv_BN, but the `fuse` function seems never been used durting the training or inference. So, can I use the standard conv and bn to replace Conv_BN?

**Comment by wkcn** [comment]
Thanks for your attention to our work!

The function `fuse` is used to fuse the conv and the batch norm into a conv for inference. I did not call it in the code.

You can replace `Conv2d_BN` by a standard conv and bn. Please notice the weight initialization of batch norm (https://github.com/microsoft/Cream/blob/main/TinyViT/models/tiny_vit.py#L28).
