### ISSUE TITLE
how to get the model  CLIP-ViT-Large/16?

### ISSUE THREAD

**Issue by liudq521** [microsoft/Cream#138]

**Comment by wkcn** [comment]
Hi @liudq521, thanks for your attention to our work!

We fine-tune the vision branch of CLIP-ViT-Large/16 model on ImageNet-22k, and the finetuned checkpoint can be downloaded from [the link](https://github.com/wkcn/TinyViT-model-zoo/releases/download/pretrained_teacher/clip_vit_large_patch14_22k.pth). The 22k classification head is randomly initialized.

Reference: https://github.com/microsoft/Cream/blob/main/TinyViT/docs/SAVE_TEACHER_LOGITS.md

**Comment by liudq521** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，我将尽快给你回复。谢谢~
