### ISSUE TITLE
weights for model pre-trained on ImageNet-22k w/o the fast pretraining distillation.

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [microsoft/Cream#140]
Thanks for this work!

Can you kindly provide the tiny-vit weights for the model pre-trained on ImageNet-22k **w/o** the fast pretraining distillation?

**Comment by ZhangYuanhan-AI** [comment]
And the weights for DeiT-S w and w/o distillation.

**Comment by wkcn** [comment]
Thanks for your attention to our work!

Sorry for late reply. We need to discuss about the release of these models. I will send the download link to you if available. 

Thank you!

**Comment by ZhangYuanhan-AI** [comment]
> Thanks for your attention to our work!
> 
> Sorry for late reply. We need to discuss about the release of these models. I will send the download link to you if available.
> 
> Thank you!

Thanks, my email is yuanhan002@e.ntu.edu.sg
