### ISSUE TITLE
what is the purpose of class 'RelativePosition2D' in AutoFormer?

### ISSUE THREAD

**Issue by mxjecho** [microsoft/Cream#145]
Hi, I'm confused as to why the calss 'RelativePosition2D_super' was used in AutoFormer? There is no such operation in the vit code of timm.

**Comment by wkcn** [comment]
Hi @mxjecho , thanks for your attention to our work.

RelativePosition2D is not a part in the original version of ViT. It is introduced to capture local information for better accuracy.

**Comment by mxjecho** [comment]
@wkcn Thanks for your reply. Is there any relevant paper for reference?

**Comment by wkcn** [comment]
Our paper [Rethinking and Improving Relative Position Encoding for Vision Transformer](https://openaccess.thecvf.com/content/ICCV2021/html/Wu_Rethinking_and_Improving_Relative_Position_Encoding_for_Vision_Transformer_ICCV_2021_paper.html) discusses the effects of 2D relative position encoding on vision transformer : )

**Comment by mxjecho** [comment]
Thanks!
