### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by nbl97** [microsoft/Cream#15]
tool/train.py 中，logger.info 并不是在所有 0 号进程中使用的，在另外的进程中 logger.info 会报错，比如 148 和 173 行。

**Comment by Z7zuqer** [comment]
Hi,

这个并不算一个bug，因为进入#148和#173时，程序已经因为没有找到训练数据而进入退出环节。不过出于规范而言，应该在每个logger.info前面加上判断local_rank是否为0.

Best,
Hao.
