### ISSUE TITLE
Maybe rpe_attenfuntion_function block has a little problem, this is my viewpoint.

### ISSUE THREAD

**Issue by yuluo-kuaiyirensheng** [microsoft/Cream#157]
The variable attn_output_weights_view is not used after you add the rpe_q or rpe_k.

**Comment by wkcn** [comment]
Hi @yuluo-kuaiyirensheng , thanks for your attention to our work!

`attn_output_weights_view` is a view of [`attn_output_weights`](https://github.com/microsoft/Cream/blob/main/iRPE/DETR-with-iRPE/models/rpe_attention/rpe_attention_function.py#L324).
When updating `attn_output_weights_view`, `attn_output_weights` is also updated, namely adding rpe_q or rpe_k.

**Comment by yuluo-kuaiyirensheng** [comment]
Thank you, I have got it. I debuged the code just now. Just like you said, i found that attn_output_weights is the same as attn_output_weights_view.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Cream"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月14日(星期二) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Cream] Maybe rpe_attenfuntion_function block has a little problem, this is my viewpoint. (Issue #157)





 
Hi @yuluo-kuaiyirensheng , thanks for your attention to our work!
 
attn_output_weights_view is a view of attn_output_weights.
 When updating attn_output_weights_view, attn_output_weights is also updated, namely adding rpe_q or rpe_k.
