### ISSUE TITLE
UserWarning: [WARNING] The module `rpe_ops` is not built. For better training performance, please build `rpe_ops`.

### ISSUE THREAD

**Issue by nanle771** [microsoft/Cream#159]
Why did I execute
cd rpe_ ops/
python setup.py install --user
And displays successful installation; But there were still errors during training
UserWarning: [WARNING] The module `rpe_ ops` is not built.  For better training performance, please build `rpe_ ops`.

**Comment by wkcn** [comment]
Thanks for your attention to our work!

Could you please check `from rpe_ops.rpe_index import RPEIndexFunction` in Python shell?

**Comment by wkcn** [comment]
Close it. Feel free to re-open it if the issue exists.

**Comment by MurphyYe** [comment]
I also have this question. I can't deal with this issue.
