### ISSUE TITLE
lib/models/blocks/inverted_residual_block.py 未被调用，有意为之还是？

### ISSUE THREAD

**Issue by nbl97** [microsoft/Cream#16]
build_supernet.py 中头文件顺序为
`from lib.models.blocks import get_Bottleneck, InvertedResidual`
`from timm.models.efficientnet_blocks import *`
所以所有的 InvertedResidual 模块只会调用 timm库的，不会调用 lib.models.blocks中的。虽然内容一样，不过容易让人混淆。

**Comment by Z7zuqer** [comment]
Hi,

1）所有的inverted residual模块确会调用timm库的内容

2）对于NAS而言，search space不应该仅局限于某一类型的operation，应该从无限的搜索空间中寻找到最佳解。故我们期望于后续的工作中引入更多的operation到search space中，使得算法更加完善。故定义了lib.models.blocks模块，方便后续增加更多的operation。

Best,
Hao.
