### ISSUE TITLE
Unable to run Mini-DeiT on CIFAR100

### ISSUE THREAD

**Issue by adarshpalaskar1** [microsoft/Cream#162]
Hello, I was trying to reproduce the  results of [Mini-DeiT](https://github.com/microsoft/Cream/tree/main/MiniViT/Mini-DeiT) on CIFAR 100 dataset by running:

`python main.py --model mini_deit_tiny_patch16_224 --batch-size 128 --data-set CIFAR100 --output_dir ./outputs  --teacher-model regnety_160 --distillation-type soft --distillation-alpha 1.0 --drop-path 0.0`

I do not have multiple GPUs and therefore not using `rpe_ops` module and have modified the script. The original script given in the README file is :
`python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --model mini_deit_tiny_patch16_224 --batch-size 128 --data-path ./ImageNet --output_dir ./outputs  --teacher-model regnety_160 --distillation-type soft --distillation-alpha 1.0 --drop-path 0.0`

I am getting the following error:
``  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/datasets01' ``

Can anyone help me fix this issue?

**Comment by adarshpalaskar1** [comment]
Resolved:

The code uses the default path /datases01 even for other datasets. Setting the `--data-path`` to a new directory solved the issue. The following command can be used:
`` python -m torch.distributed.launch --use_env main.py --model mini_deit_small_patch16_224 --batch-size 128 --data-path ./cifar100 --data-set CIFAR100 --output_dir ./outputs  --teacher-model regnety_160 --distillation-type soft --distillation-alpha 1.0 --drop-path 0.0 ``

**Comment by wkcn** [comment]
Thanks for pointing it out!
