### ISSUE TITLE
EfficientVit's inference and ONNX convert

### ISSUE THREAD

**Issue by alexliyang** [microsoft/Cream#173]
hi, your work is amazing. Can you share the inference test code and convert to onnx code?
thx.

**Comment by xinyuliu-jeffrey** [comment]
Hi @alexliyang ,

Thanks for your interest! For inference, please follow the provided instructions here: https://github.com/microsoft/Cream/tree/main/EfficientViT/classification#evaluation. For onnx convert, just follow the instructions [here](https://pytorch.org/docs/stable/onnx.html) and use the torch.onnx.export function:
`torch.onnx.export(model, dummy_inputs, onnx_fname, export_params=True, verbose=False, training=torch.onnx.TrainingMode.EVAL, opset_version=11)
`
