### ISSUE TITLE
error when use the tinyvit

### ISSUE THREAD

**Issue by AmberCheng** [microsoft/Cream#175]
model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_cfg'

Hi, I have met the error when I try to use the code:
```
from tiny_vit import tiny_vit_21m_224
model = tiny_vit_21m_224(pretrained=True)
output = model(image)
```
I wonder do I miss something?

**Comment by wkcn** [comment]
Hi @AmberCheng , thanks for your attention tou our work!

It seems to be related to timm version.

Could you please upgrade timm (version>=0.4.12) by the following command?
```bash
pip install timm==0.4.12
```

Check the version of timm
```bash
python -c "import timm; print(timm.__version__)"
```

**Comment by AmberCheng** [comment]
> 
Actually, I found that the version of my timm is timm-0.6.11. And I tried the 0.4.12, it works! I appreciate for your help!

**Comment by wkcn** [comment]
Thanks for pointing the bug out! I will make it compatible with timm-0.6.11.

**Comment by wkcn** [comment]
The latest code supports timm>=0.6.11 now.

Close the issue. Feel free to reopen it if any problem.
