### ISSUE TITLE
EfficientViT: benchmark code for onnx

### ISSUE THREAD

**Issue by jameslahm** [microsoft/Cream#177]
Thanks for your great work! Would you mind sharing the benchmark code for onnx? Thanks!

**Comment by xinyuliu-jeffrey** [comment]
Hi @jameslahm ,

Thanks for your interest in our work! 

The part of onnx throughput benchmarking is included in some private projects, so we may not be able to release it directly at present. However, you may implement an onnx throughput inference script by referencing [official onnxruntime doc](https://onnxruntime.ai/docs/get-started/with-python.html#pytorch-cv) and [speed_test](https://github.com/microsoft/Cream/blob/main/EfficientViT/classification/speed_test.py) jointly. Please feel free to contact me if there are any other questions. Thanks!

Best,
Xinyu

**Comment by jameslahm** [comment]
Thanks!
