### ISSUE TITLE
question about Fig 4 in EfficientViT

### ISSUE THREAD

**Issue by ysj9909** [microsoft/Cream#178]
Thanks for sharing your code of work,
In Figure 4, could you explain how the similarity with each head was calculated?

Thank you!

**Comment by xinyuliu-jeffrey** [comment]
Hi @ysj9909 ,

Thanks for your interest in our work. For each layer, the maximum cosine similarity value is Max_i(Max_j(CosineSim(feat(i-th head), feat(j-th head)))) (j!=i). Then, the value is averaged for all batches. 

Best,
Xinyu
