### ISSUE TITLE
Tiny-ViT has been used in MobileSAM to make the image encoder in SAM 100 times smaller

### ISSUE THREAD

**Issue by ChaoningZhang** [microsoft/Cream#181]
Tiny-ViT has been used in MobileSAM to make the image encoder in SAM 100 times smaller.
We have found that your Tiny-ViT is very powerful and adopted for our MobileSAM project.
We thank the authors of Tiny-ViT very much for their excellent work.

**Comment by wkcn** [comment]
I'm so happy to hear this! Thank you so much for referencing our work in your MobileSAM paper! I'm pleased to see the excellent results achieved in your research : )
