### ISSUE TITLE
EfficientViT: code for downstream image classification

### ISSUE THREAD

**Issue by jameslahm** [microsoft/Cream#182]
Thank you for your great work! Would you mind sharing the code for downstream image classification in Table 4 in the paper? Thanks a lot!

**Comment by xinyuliu-jeffrey** [comment]
Hi @jameslahm ,

Sure, the training on downstream please follow the instructions for Imagenet classification. Please kindly use [this file](https://github.com/microsoft/Cream/blob/main/AutoFormer/lib/datasets.py) to build the downstream datasets ;)

Best,
Xinyu

**Comment by jameslahm** [comment]
Thanks!
