### ISSUE TITLE
TinyCLIP link in README leads to 404

### ISSUE THREAD

**Issue by mrdbourke** [microsoft/Cream#184]
Hi there,

The TinyCLIP link on the front page of the README leads to a 404 link (see screenshot).

Searching the repo, I can't seem to find the paper/code?

Is this an error or is the paper not out quite yet?

Either way, thank you for the excellent repo, looking forward to reading about TinyCLIP.

Best,

Daniel

<img width="1086" alt="Screenshot 2023-09-05 at 12 59 40 pm" src="https://github.com/microsoft/Cream/assets/16750345/fad9f7cb-6bfd-428e-b35e-ec643987e1d6">

**Comment by wkcn** [comment]
Hi @mrdbourke , thanks for your attention to our work!

TinyCLIP is a cross-modal distillation method for CLIP-like models.
It has been accepted by ICCV 2023, and we will release the paper, the code and model checkpoints soon : )

**Comment by mrdbourke** [comment]
Thank you for the heads up! Looking forward to it :)
