### ISSUE TITLE
[tinyclip] AttributeError: 'ModifiedResNet' object has no attribute 'transformer'

### ISSUE THREAD

**Issue by chuchienshu** [microsoft/Cream#200]
![image](https://github.com/microsoft/Cream/assets/25679333/9ba407ae-893b-426a-8482-46e02f011f0e)

It comes to abovementioned  AttributeError if setting `--model "TinyCLIP-ResNet-19M-Text-19M" ` insider manual_weight_inherit_100to75.sh. but there is another error when setting `--model "TinyCLIP-ViT-39M-16-Text-19M"`  :
![image](https://github.com/microsoft/Cream/assets/25679333/da7cb622-c0df-44e4-9982-b47a07522a0d)
any advice will be helpful. thx  @wkcn

**Comment by wkcn** [comment]
Hi @chuchienshu , I have fixed the bug in the latest code.
When the student model is `TinyCLIP-ViT-39M-16-Text-19M`, the `--pretrained-image-file` and `--pretrained-text-file` should be `ViT-B-16@laion400m_e32`. The `--distillation-teacher` can be `ViT-B-32@laion2b_e16`.

**Comment by chuchienshu** [comment]
> TinyCLIP-ViT-39M-16-Text-19M

Hi @wkcn . Thanks for your hotfix! and now we get `RuntimeError: Model config for ViT-B-16 not found.` when setting params as your suggestion. Seems like essential config file been ignored. looking forward to have it back. BTW, is it possible to distill a `resnet `student model?

**Comment by wkcn** [comment]
@chuchienshu  Sorry that I forgot to add the model config `ViT-B-16.json` from https://github.com/mlfoundations/open_clip/tree/main/src/open_clip/model_configs.

Now it works. 

> is it possible to distill a resnet student model?

Yes. We can distill the knowledge from the teacher model CLIP-ViT to the student model CLIP-ResNet.

**Comment by wkcn** [comment]
Close it. Feel free to reopen it if the issue still exists. : )
