### ISSUE TITLE
do you provide pre trained models for EfficientVit on your end？

### ISSUE THREAD

**Issue by Idol-Dou2021** [microsoft/Cream#208]
I want to load a pre trained model and then train it, but I don't have it. Can you provide it？

**Comment by xinyuliu-jeffrey** [comment]
Hi @Idol-Dou2021 ,

Thanks for your interest in our work. The pretrained models are provided here https://github.com/microsoft/Cream/blob/main/EfficientViT/classification/README.md#model-zoo

Best,
Xinyu

**Comment by xinyuliu-jeffrey** [comment]
Close the issue. Feel free to reopen it if any problem.
