### ISSUE TITLE
About the conversion of EfficientViT

### ISSUE THREAD

**Issue by eehoeskrap** [microsoft/Cream#211]
Is it impossible to convert the EfficientViT model to the tflite model?

**Comment by xinyuliu-jeffrey** [comment]
@eehoeskrap Thanks for your interest in our work. We have provided the converted ONNX models, you may try using (ONNX-tensorflow)[https://github.com/onnx/onnx-tensorflow] and following the instructions in (this repo)[https://github.com/sithu31296/PyTorch-ONNX-TFLite] to convert the models to TFLite.
