### ISSUE TITLE
TinyCLIP HuggingFace integration

### ISSUE THREAD

**Issue by FransHk** [microsoft/Cream#212]
Hi team,

I am integrating and comparing the brilliant set of TinyCLIP (ViT-based) architectures with the vanilla CLIP model in a number of language-enabled action recognition frameworks. Some of these AR models rely on HF model configurations, are there plans to release the TinyCLIP family to HF? Thanks!

**Comment by wkcn** [comment]
Hi @FransHk , thanks for your attention to our work!

Were you referring to integrating TinyCLIP into Hugging Face, like this example?
https://huggingface.co/openai/clip-vit-large-patch14

**Comment by FransHk** [comment]
Hi, thanks for your reply. You are right. I am looking to export a TinyCLIP model in the HuggingFace 'ClipConfig' format so that I can load it into an existing codebase that expects this format.

For example, the code I am integrating TinyCLIP in loads vanilla CLIP like so:

`from transformers import CLIPModel, CLIPConfig`

```
configuration = CLIPConfig().from_pretrained(pretrained_model)
clip_model = CLIPModel.from_pretrained(pretrained_model, config=configuration)
```

The model that integrates CLIP for AR tasks is completely built around the HF-formatted CLIP, that's why I'm asking instead of re-implementing it for the open clip framework. Does this answer your question?

**Comment by wkcn** [comment]
I see. Thanks @FransHk !

I am trying to integrate TinyCLIP into HF. 
I rarely use transformers, and I have encountered issues with CLIPConfig, so it will take some time to integrate TinyCLIP :)

**Comment by FransHk** [comment]
Thank you @wkcn, looking forward to the results!

**Comment by wkcn** [comment]
Hi @FransHk, I have integrated some TinyCLIP-ViT models into HF.

https://huggingface.co/collections/wkcn/tinyclip-model-zoo-6581aa105311fe07be88cb0d

**Comment by becxer** [comment]
@wkcn Could you guide me how to convert "open_clip TinyCLIP.pt" model to "HF TinyCLIP" ?
I found order of transformer layers are changed and some parameters are missing.

**Comment by wkcn** [comment]
Hi @becxer , I used the script (https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/convert_clip_original_pytorch_to_hf.py) to convert the model.

The number of layers in config.json should be changed like https://huggingface.co/wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M/blob/main/config.json#L138.

**Comment by becxer** [comment]
> Hi @becxer , I used the script (https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/convert_clip_original_pytorch_to_hf.py) to convert the model.
> 
> The number of layers in config.json should be changed like https://huggingface.co/wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M/blob/main/config.json#L138.

Appreciates for the quick response!
So did you mean that the following PT model can be converted into the following HF model using the mentions script without additional training?

PT : https://github.com/wkcn/TinyCLIP-model-zoo/releases/download/checkpoints/TinyCLIP-ViT-40M-32-Text-19M-LAION400M.pt    

HF : https://huggingface.co/wkcn/TinyCLIP-ViT-40M-32-Text-19M-LAION400M

**Comment by wkcn** [comment]
@becxer Yes. The conversion does not need additional training.
