### ISSUE TITLE
IRPE: About the shape of Wq,Wk,Wv’

### ISSUE THREAD

**Issue by Zhong1015** [microsoft/Cream#229]
@wkcn 
Hello, your work is inspiring. Recently, while looking at Figure 1, I had a bit of confusion. You have noted '1x1' after Wq, Wk, Wv, which makes me think you are using weight matrices of size 1x1. However, this contradicts my previous understanding. Another interpretation I have is: 1x1 indicates the need to first reduce the dimensionality of x, and then pass through the Wq, Wk, and Wv matrices. I would like to know if my understanding of this part is correct.
![屏幕截图 2024-03-19 202425](https://github.com/microsoft/Cream/assets/148180091/56d5f012-27ce-4673-bc58-b976028fab19)

**Comment by wkcn** [comment]
Hi @Zhong1015 ,  the shape of Wq, Wk and Wv are all (dim, dim).
We annotated 1x1 which represents a 1x1 operation on 2-D space, where each token is projected independently.

We referred to the figure 2 of non-local neural network (https://arxiv.org/pdf/1711.07971.pdf).

<img width="795" alt="image" src="https://github.com/microsoft/Cream/assets/3415417/a42b0ca0-b5c1-4cfa-ad02-cb35750af48b">

**Comment by Zhong1015** [comment]
Thank you for your reply! I think this can help me a lot!

**Comment by Zhong1015** [comment]
> Hi @Zhong1015 , the shape of Wq, Wk and Wv are all (dim, dim). We annotated 1x1 which represents a 1x1 operation on 2-D space, where each token is projected independently.
> 
> We referred to the figure 2 of non-local neural network (https://arxiv.org/pdf/1711.07971.pdf).
> 
> <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/3415417/314337676-a42b0ca0-b5c1-4cfa-ad02-cb35750af48b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTAxNDMsIm5iZiI6MTcxMDkwOTg0MywicGF0aCI6Ii8zNDE1NDE3LzMxNDMzNzY3Ni1hNDJiMGNhMC1iNWMxLTRjZmEtYWQwMi1jYjM1NzUwYWY0OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDQ0NDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUyZWM1ZjJmNDcxMGRjYzIxYWRhZmU1NzYyMzczZGYzODlkMTZjZTE0ZThlZWVjNTAyZjljYWUyMTEzOWE2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gy3pmzsgPDMUIpPyPOlqJwxJLVFdCJr1L9SuWTtvKsk">
I read the paper you provided. They mentioned in the paper that 1x1 convolution is used for dimensionality reduction. However, when using IRPE, in practice, according to the initial operations of the transformer, the input needs to undergo a linear transformation to obtain QKV (Query, Key, Value). Is this linear transformation operation actually performed in Figure 1, although it is not specifically indicated on the figure?

**Comment by wkcn** [comment]
@Zhong1015 
> Is this linear transformation operation actually performed in Figure 1?

Yes. The linear transformation is the same as that in self-attention.

https://github.com/microsoft/Cream/blob/main/iRPE/DeiT-with-iRPE/rpe_vision_transformer.py#L70
