### ISSUE TITLE
dear teachers, could you please provide ResNet-30M script distilled in yfcc15m? How long does it take to train on an A100， thanks!!

### ISSUE THREAD

**Issue by leo23ui** [microsoft/Cream#245]

**Comment by wkcn** [comment]
Hi @leo23ui , you can refer to the script: https://github.com/microsoft/Cream/blob/main/TinyCLIP/script/manual_weight_inherit_100to75.sh

The different arguments:
```
--model TinyCLIP-ResNet-30M-Text-29M
--pretrained-image-file RN50@openai
--pretrained-text-file RN50@openai
```

The configurations of models:

Model | Vision Layers | Vision width | Text Layers | Text Width | Text Heads
-|-|-|-|-|-
RN50 | 3,4,6,3 | 64 | 12 | 512 | 8
TinyCLIP-ResNet-30M-Text-29M | 3,4,6,3 | 56 | 9 | 512 | 8 
TinyCLIP-ResNet-19M-Text-19M | 3,4,6,3 | 44 | 6 | 512 | 8

The training throughput on an A100-SXM4-40GB GPU may be 588 pairs/s. It takes 7 hours on YFCC-15M for 1 epoch.

**Comment by leo23ui** [comment]
> Hi [@leo23ui](https://github.com/leo23ui) , you can refer to the script: https://github.com/microsoft/Cream/blob/main/TinyCLIP/script/manual_weight_inherit_100to75.sh
> 
> The different arguments:
> 
> ```
> --model TinyCLIP-ResNet-30M-Text-29M
> --pretrained-image-file RN50@openai
> --pretrained-text-file RN50@openai
> ```
> 
> The configurations of models:
> 
> Model	Vision Layers	Vision width	Text Layers	Text Width	Text Heads
> RN50	3,4,6,3	64	12	512	8
> TinyCLIP-ResNet-30M-Text-29M	3,4,6,3	56	9	512	8
> TinyCLIP-ResNet-19M-Text-19M	3,4,6,3	44	6	512	8
> The training throughput on an A100-SXM4-40GB GPU may be 588 pairs/s. It takes 7 hours on YFCC-15M for 1 epoch.

thanks for your reply!!
