### ISSUE TITLE
Hello, could you please provide the model.bin file of CLIP ViT-B/16 12 512 86+38 20.5 818 YFCC-15M model? Looking forward to your reply, thanks!!!

### ISSUE THREAD

**Issue by leo23ui** [microsoft/Cream#251]
Hello, could you please provide the model.bin file of CLIP ViT-B/16 12 512 86+38 20.5 818 YFCC-15M model? Looking forward to your reply, thanks!!!
![Image](https://github.com/user-attachments/assets/b4a07def-9824-4ff5-9ef5-bff21aa533fc)

**Comment by wkcn** [comment]
The results refer to the paper [46, 38].

**Comment by leo23ui** [comment]
> The results refer to the paper [46, 38].

Thank you for your reply!!!, Could you please give me CLIP ViT-B/16 12 512 86+38 20.5 818 YFCC-15M's zeroshot accuracy on cifar10, cifar100, tiny-imagenet, fairface-age, fairface-gender, and fairface-group, could I invite you to drink milk tea, thanks very much!!! I provide six evaluate codes and four datasets in the google drive for convinience, hope to get your reply, thanks!!!

**Comment by wkcn** [comment]
We have no plan to do it.

**Comment by leo23ui** [comment]
> We have no plan to do it.

thanks for your reply!!! thanks very much for your help
