### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by macn3388** [microsoft/Cream#4]
Hello,

Thanks for your great work! Your idea is brilliant!

When i tried to run 'python ./tools/main.py train ./experiments/configs/train/train.yaml', it looks like something wrong happend in backpropagation:

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
11/06 02:53:08 PM | Training on Process 0 with 2 GPUs.
11/06 02:53:09 PM | Supernet created, param count: 29809073
11/06 02:53:09 PM | resolution: 224
11/06 02:53:09 PM | choice number: 6
11/06 02:53:15 PM | Using torch DistributedDataParallel. Install NVIDIA Apex for Apex DDP.
11/06 02:53:15 PM | Scheduled epochs: 120
11/06 02:53:31 PM | Train: 0 [   0/5004 (  0%)]  Loss:  6.901703 (6.9017)  KD-Loss:  0.000000 (0.0000)  Prec@1:  0.0000 ( 0.0000)  Prec@5:  0.0000 ( 0.0000)  Time: 1.926s,  132.92/s  (1.926s,  132.92/s)  LR: 5.000e-01  Data: 1.326 (1.326)
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main()
  File "tools/train.py", line 217, in main
    est=model_est, local_rank=args.local_rank)
  File "/home/tiger/Cream/tools/../lib/core/train.py", line 51, in train_epoch
    output = model(input, random_cand)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 459, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:518)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7efbdb652273 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x734 (0x7efc25d088e4 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x69795c (0x7efc25cf795c in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1d3ab4 (0x7efc25833ab4 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x254 (0x55b1da967744 in /opt/tiger/conda/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x55b1da967861 in /opt/tiger/conda/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x52f8 (0x55b1da9d36e8 in /opt/tiger/conda/bin/python)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x55b1da917539 in /opt/tiger/conda/bin/python)
frame #8: _PyFunction_FastCallDict + 0x1d5 (0x55b1da918635 in /opt/tiger/conda/bin/python)
frame #9: _PyObject_Call_Prepend + 0x63 (0x55b1da936e53 in /opt/tiger/conda/bin/python)
frame #10: PyObject_Call + 0x6e (0x55b1da929dbe in /opt/tiger/conda/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x1e42 (0x55b1da9d0232 in /opt/tiger/conda/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x55b1da917539 in /opt/tiger/conda/bin/python)
frame #13: _PyFunction_FastCallDict + 0x1d5 (0x55b1da918635 in /opt/tiger/conda/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x55b1da936e53 in /opt/tiger/conda/bin/python)
frame #15: <unknown function> + 0x16ba3a (0x55b1da96ea3a in /opt/tiger/conda/bin/python)
frame #16: _PyObject_FastCallKeywords + 0x49b (0x55b1da96f8fb in /opt/tiger/conda/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x4a96 (0x55b1da9d2e86 in /opt/tiger/conda/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x55b1da917539 in /opt/tiger/conda/bin/python)
frame #19: _PyFunction_FastCallKeywords + 0x387 (0x55b1da966f57 in /opt/tiger/conda/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x14dc (0x55b1da9cf8cc in /opt/tiger/conda/bin/python)
frame #21: _PyFunction_FastCallKeywords + 0xfb (0x55b1da966ccb in /opt/tiger/conda/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x416 (0x55b1da9ce806 in /opt/tiger/conda/bin/python)
frame #23: _PyEval_EvalCodeWithName + 0x2f9 (0x55b1da917539 in /opt/tiger/conda/bin/python)
frame #24: PyEval_EvalCodeEx + 0x44 (0x55b1da918424 in /opt/tiger/conda/bin/python)
frame #25: PyEval_EvalCode + 0x1c (0x55b1da91844c in /opt/tiger/conda/bin/python)
frame #26: <unknown function> + 0x22ab74 (0x55b1daa2db74 in /opt/tiger/conda/bin/python)
frame #27: PyRun_FileExFlags + 0xa1 (0x55b1daa37eb1 in /opt/tiger/conda/bin/python)
frame #28: PyRun_SimpleFileExFlags + 0x1c3 (0x55b1daa380a3 in /opt/tiger/conda/bin/python)
frame #29: <unknown function> + 0x236195 (0x55b1daa39195 in /opt/tiger/conda/bin/python)
frame #30: _Py_UnixMain + 0x3c (0x55b1daa392bc in /opt/tiger/conda/bin/python)
frame #31: __libc_start_main + 0xeb (0x7efc2c63309b in /lib/x86_64-linux-gnu/libc.so.6)
frame #32: <unknown function> + 0x1db062 (0x55b1da9de062 in /opt/tiger/conda/bin/python)

Is there any solution?

**Comment by macn3388** [comment]
passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel` soved this problem

**Comment by mapleam** [comment]
Hi,

Thanks for your kind question~!

Could you share the environment variables with us? We haven't encounter such problems using this code base.

Really appreciate you could reply.

Best.
Hao.

**Comment by macn3388** [comment]
> Hi,
> 
> Thanks for your kind question~!
> 
> Could you share the environment variables with us? We haven't encounter such problems using this code base.
> 
> Really appreciate you could reply.
> 
> Best.
> Hao.

python 3.7.4
torch 1.2.0
