### ISSUE TITLE
About Figure 4

### ISSUE THREAD

**Issue by CocaIceCola7759** [microsoft/Cream#53]
The curve of Figure 4 in the paper is drawn based on the results of Autoformer-base.

Could you provide me with a curve drawn based on the results of Autoformer-tiny?

Do you still save the output log of Autoformer tiny/small/base while training?

I want to compare  with my current results.

Thanks!

**Comment by silent-chen** [comment]
Hi,

Thanks for your interest in our work. For the request for the training logs of AutoFormer models, could you drop me an email? The email address is minghao.chen@stonybrook.edu.

Best,

**Comment by CocaIceCola7759** [comment]
> Hi,
> 
> Thanks for your interest in our work. For the request for the training logs of AutoFormer models, could you drop me an email? The email address is [minghao.chen@stonybrook.edu](mailto:minghao.chen@stonybrook.edu).
> 
> Best,

Thanks! I got it.

**Comment by CocaIceCola7759** [comment]
> Hi,
> 
> Thanks for your interest in our work. For the request for the training logs of AutoFormer models, could you drop me an email? The email address is [minghao.chen@stonybrook.edu](mailto:minghao.chen@stonybrook.edu).
> 
> Best,

I have sent an email to minghao.chen@stonybrook.edu, please check it, thank you very much!
