### ISSUE TITLE
Is the objective of evolutional search in AutoFormer multi-objective?

### ISSUE THREAD

**Issue by ParadoxZW** [microsoft/Cream#54]
Since the paper says, "Our objective here is to maximize the classification accuracy while minimizing the model size", which kind of multi-objective evolutional algorithm do you use?

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our paper. We set an upper bound of model size during the evolution algorithm. For the evolution algorithm, we use the genetic evolution algorithm.

**Comment by ParadoxZW** [comment]
I mean, the objective of the evolution algorithm here is just accuracy, or the combination of accuracy and model size(i.e. multi-objective)?

**Comment by silent-chen** [comment]
The objective is to maximize the accuracy under a specific computation constraint.

**Comment by ZLKong** [comment]
> Hi, thanks for your interest in our paper. We set an upper bound of model size during the evolution algorithm. For the evolution algorithm, we use the genetic evolution algorithm.

How do I set the param limit?  The AutoFormer-base result, for example, do I set it like --min-param-limits 54 --param-limits 55?
