### ISSUE TITLE
How to load 3D images into the AutoFormer architecture

### ISSUE THREAD

**Issue by Harsh-Gill** [microsoft/Cream#65]
I am trying to modify the AutoFormer code to allow 3D images then combine a custom decoder. However, I am having trouble on modifying for 3D, any advise on how I can do so? Thanks

**Comment by silent-chen** [comment]
One simple way is to split the 3D images into multiple 2D images and feed them to AutoFormer. Another way is to split the 3D images into many small patches and embed them. Remember to modify the position embeddings to make the architecture reasonable.

**Comment by silent-chen** [comment]
Hi @Harsh-Gill. Hope you have solved the problem. I will close the issue now. If you have further questions, feel free to reopen it.
