### ISSUE TITLE
Modify supernet for finetuning on a different dataset

### ISSUE THREAD

**Issue by hamdjalil** [microsoft/Cream#66]
I tried using checkpoints for supernet for training a different dataset but I'm getting a size mismatch error:

`python supernet_train.py --data-path .\dslr_split --gp --change_qk --relative_position --mode super --dist-eval --cfg .\experiments\supernet\supernet-B.yaml --resume .\supernet-base.pth --epochs 600 --warmup-epochs 20 --output .\outputs1_B_ft_500_dslr --batch-size 32`

Not using distributed mode

Namespace(aa='rand-m9-mstd0.5-inc1', amp=True, batch_size=32, cfg='.\\experiments\\supernet\\supernet-B.yaml', change_qkv=True, clip_grad=None, color_jitter=0.4, cooldown_epochs=10, cutmix=1.0, cutmix_minmax=None, data_path='.\\dslr_split', data_set='AMZN', decay_epochs=30, decay_rate=0.1, device='cuda', dist_eval=True, dist_url='env://', distributed=False, drop=0.0, drop_block=None, drop_path=0.1, epochs=600, eval=False, gp=True, inat_category='name', input_size=224, lr=0.0005, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, lr_power=1.0, max_relative_position=14, min_lr=1e-05, mixup=0.8, mixup_mode='batch', mixup_prob=1.0, mixup_switch_prob=0.5, mode='super', model='', model_ema=False, model_ema_decay=0.99996, model_ema_force_cpu=False, momentum=0.9, no_abs_pos=False, num_workers=10, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='.\\outputs1_B_ft_500_dslr', patch_size=16, patience_epochs=10, pin_mem=True, platform='pai', post_norm=False, recount=1, relative_position=True, remode='pixel', repeated_aug=True, reprob=0.25, resplit=False, resume='.\\supernet-base.pth', rpe_type='bias', sched='cosine', seed=0, smoothing=0.1, start_epoch=0, teacher_model='', train_interpolation='bicubic', warmup_epochs=20, warmup_lr=1e-06, weight_decay=0.05, world_size=1)
Creating SuperVisionTransformer
{'SUPERNET': {'MLP_RATIO': 4.0, 'NUM_HEADS': 10, 'EMBED_DIM': 640, 'DEPTH': 16}, 'SEARCH_SPACE': {'MLP_RATIO': [3.0, 3.5, 4.0], 'NUM_HEADS': [9, 10], 'DEPTH': [14, 15, 16], 'EMBED_DIM': [528, 576, 624]}}
number of params: 79539231
Traceback (most recent call last):
  File "supernet_train.py", line 397, in <module>
    main(args)
  File "supernet_train.py", line 323, in main
    model_without_ddp.load_state_dict(checkpoint['model'])
  File "C:\Users\iqbal\.conda\envs\Autoformer\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Vision_TransformerSuper:
        size mismatch for head.weight: copying a param with shape torch.Size([1000, 640]) from checkpoint, the shape in current model is torch.Size([31, 640]).
        size mismatch for head.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([31]).

Can you please let me know what exactly I'm doing wrong? Thanks

**Comment by hamdjalil** [comment]
Since I was trying to finetune on a different dataset, I realized the head of the supernet has to be modified,

after the checkpoints are loaded with the supernet at` line 327` , I use `model_without_ddp.reset_classifier(31`) to change the head, however I get the following error :
Traceback (most recent call last):
  File "supernet_train2.py", line 409, in <module>
    main(args)
  File "supernet_train2.py", line 368, in main
    choices=choices, mode = args.mode, retrain_config=retrain_config,
  File "E:\DataTemp\Asim\Hamd\NeurAI\Cream\AutoFormer\supernet_engine.py", line 57, in train_one_epoch
    model_module.set_sample_config(config=config)
  File "E:\DataTemp\Asim\Hamd\NeurAI\Cream\AutoFormer\model\supernet_transformer.py", line 129, in set_sample_config
    self.head.set_sample_config(self.sample_embed_dim[-1], self.num_classes)
  File "C:\Users\iqbal\.conda\envs\Autoformer\lib\site-packages\torch\nn\modules\module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Linear' object has no attribute 'set_sample_config'

**Comment by silent-chen** [comment]
Dear hamdjalil,

Thanks for your interest in our work. If you what finetune AutoFormer on a different dataset, you should load all the state_dict of the pretrained supernet without the "head". The output number of the classification head is decided by the argument "args.nb_classes". Therefore, you should specify that args.nb_classes to be 31 when defining the network architecture and delete the weights of the classification head before loading the state_dict.  Here is the codes for deleting the weights of the head in state_dict.
```
for k in ['head.weight', 'head.bias']:
   if k in checkpoint_model and checkpoint_model[k].shape != state_dict[k].shape:
      print(f"Removing key {k} from pretrained checkpoint")
      del checkpoint_model[k]
```

**Comment by hamdjalil** [comment]
Thank you very much for your assistance, this was very helpful.

I have one final question, If I am to test my model, does the testing take place on validation data or do I
 need a seperate test folder when testing my models
