### ISSUE TITLE
Attention calculation

### ISSUE THREAD

**Issue by ZhuangLii** [microsoft/Cream#71]
hello sir,
 I am curious why the `attn` for key is computed by using `q` as the code below
`if self.rpe_k is not None:
            attn += self.rpe_k(q)`
why not
`if self.rpe_q is not None:
            attn += self.rpe_q(q)`
> https://github.com/microsoft/Cream/blob/main/iRPE/DETR-with-iRPE/models/rpe_attention/rpe_attention_function.py

**Comment by wkcn** [comment]
Thanks for your attention for my work : )

`rpe_k` returns the relative position encoding (RPE) on keys.

For the RPE on keys, the attention equation can be unfolded as below:
<img width="358" alt="rpe_k" src="https://user-images.githubusercontent.com/3415417/151514747-7ecf4d09-6f56-4a58-a55f-2ed4449d5c53.png">

The RPE on keys (`rpe_k`) is related to queries (`q`), so `q` is the input of the module `rpe_k`.

**Comment by ZhuangLii** [comment]
thx sir, understood!
