### ISSUE TITLE
Architecture Details of AutoFormerV2

### ISSUE THREAD

**Issue by ChuanyangZheng** [microsoft/Cream#72]
Hi, I haven't found specific architecture details of S3 model in your [**paper**](https://arxiv.org/abs/2111.14725). Similarly, I haven't  found model config parameters in github folder Cream/AutoFormerV2. Could you provide specific model paramter such as mlp ratio for AutoFormerV2 family. Thank you very much~

**Comment by liujingcs** [comment]
Thanks for the great work! I also have the same question. Can you please provide the details of the final search space?

**Comment by silent-chen** [comment]
Hi all, thanks for your interests in our paper. In figure 2, we accutally give all the search spaces include the intial one and the final search space. In specific, the final search space is the last column in every subfigure.
