### ISSUE TITLE
About the parameters configs setting of Autoformer 

### ISSUE THREAD

**Issue by ChongjianGE** [microsoft/Cream#74]
Hi, thanks for the great works on Autoformer.

I wonder how can I set the param limit configs on the searching process.
For example, would you please provide the configs for AutoFormer-base so that we will get more familiar with configuring=--min-param-limits and--param-limits.

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our work.

The param limit configs for AutoFormer-base are `` --min-param-limits 52``  and ``--param-limits 54``.

Hope this is helpful for you :).
