### ISSUE TITLE
Some wrongs with nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by hongsheng-Z** [microsoft/Cream#75]
Hi, thanks for your great work. But I have some problems when I run the following command:
cd /rpe_ops
python setup.py install --user

FAILED: /home/UserDirectory/hongshengz/Stark-main/lib/models/stark/rpe_ops/build/temp.linux-x86_64-3.8/rpe_index_cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/UserDirectory/hongshengz/Stark-main/lib/models/stark/rpe_ops/build/temp.linux-x86_64-3.8/rpe_index_cuda.o.d -DWITH_CUDA -I/home/UserDirectory/hongshengz/anaconda3/lib/python3.8/site-packages/torch/include -I/home/UserDirectory/hongshengz/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UserDirectory/hongshengz/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/UserDirectory/hongshengz/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/UserDirectory/hongshengz/anaconda3/include/python3.8 -c -c /home/UserDirectory/hongshengz/Stark-main/lib/models/stark/rpe_ops/rpe_index_cuda.cu -o /home/UserDirectory/hongshengz/Stark-main/lib/models/stark/rpe_ops/build/temp.linux-x86_64-3.8/rpe_index_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=rpe_index_cpp -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'

My  environment is:
RTX3090
CUDA:11.4  
torch_version: 1.8.1

**Comment by wkcn** [comment]
Thank you for the interest in our work : )

The reason is that the installed NVCC does not support `compute_86`.

Could you please try `TORCH_CUDA_ARCH_LIST="7.5" python setup.py install --user` to build the custom operator ?

**Comment by hongsheng-Z** [comment]
Thanks. I just tried your instructions again and still got the same error, I think maybe I need to reinstall NVCC to fix it.

**Comment by wkcn** [comment]
Hi @hongsheng-Z , have you solved the problem? If yes, I will close the issue : )

**Comment by penghouwen** [comment]
Close the issue. Feel free to reopen it if having any question.
