### ISSUE TITLE
Details parameters of the super network

### ISSUE THREAD

**Issue by sorobedio** [microsoft/Cream#76]
Hello. i have not found details of the hyper=parameters used to build your super network.
could you indicate which set of parameters used?
thank you

**Comment by silent-chen** [comment]
Hi, the supernet config is [here](https://github.com/microsoft/Cream/tree/main/AutoFormer/experiments/supernet). Hope this helpful for you.

**Comment by sorobedio** [comment]
Thank you. i was talking about the supernets used in Autoformer_v2. I guess they are the same supernets.
