### ISSUE TITLE
Training Mini-Deit-Ti 如何运行？可以在pycharm中运行吗？

### ISSUE THREAD

**Issue by DoubleHui97** [microsoft/Cream#82]
![image](https://user-images.githubusercontent.com/95152494/165328362-24bff73b-0175-43f5-b470-15a7a81e796c.png)

**Comment by wkcn** [comment]
@DoubleHui97 你好，感谢你对我们的工作的关注！

为了训练Mini-DeiT-Ti, 需要按照[README](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-DeiT/README.md)的[Usage](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-DeiT/README.md#usage)安装好Python的依赖库，以及按照[Data Preparation](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-DeiT/README.md#data-preparation)准备ImageNet数据集，

打开终端(Terminal或者ssh连接远程服务器)，进入Mini-DeiT的文件夹，运行命令：
```bash
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --model mini_deit_tiny_patch16_224 --batch-size 128 --data-path ./ImageNet --output_dir ./outputs  --teacher-model regnety_160 --distillation-type soft --distillation-alpha 1.0 --drop-path 0.0
```
其中，`--nproc_per_node`的参数8是使用的GPU数量，`--data-path`的参数是ImageNet数据集的路径，`--output_dir`的参数是Log和Checkpoint保存的路径。

也可以在PyCharm中运行，需要在PyCharm的终端(Terminal)里运行上面的命令。

**Comment by wkcn** [comment]
@DoubleHui97 请问这个问题解决了吗？

因为有两周没有回复，我暂时关掉这个问题。
如果有其他问题的话，欢迎重新打开这个Issue. : )

**Comment by DoubleHui97** [comment]
这个问题我还没有按您发我的教程操作，我后面试试再说，谢谢您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月11日(周三) 下午2:04
收件人: ***@***.***&gt;;
抄送: "Shuanghui ***@***.******@***.***&gt;;
主题: Re: [microsoft/Cream] Training Mini-Deit-Ti 如何运行？可以在pycharm中运行吗？ (Issue #82)




 
@DoubleHui97 请问这个问题解决了吗？
 
因为有两周没有回复，我暂时关掉这个问题。
 如果有其他问题的话，欢迎重新打开这个Issue. : )

**Comment by wkcn** [comment]
@DoubleHui97 不客气~欢迎提问 : )
