### ISSUE TITLE
Questions about search space of Cream

### ISSUE THREAD

**Issue by pprp** [microsoft/Cream#85]
Hi, thank you for your great work! I am interested in Cream but I met some problems when reading both the paper and the source code.

**Question 1**:

In [supernet.py](https://github.com/microsoft/Cream/blob/main/Cream/lib/models/structures/supernet.py):

```
  arch_def = [
      # stage 0, 112x112 in
      ['ds_r1_k3_s1_e1_c16_se0.25'],
      # stage 1, 112x112 in
      ['ir_r1_k3_s2_e4_c24_se0.25', 'ir_r1_k3_s1_e4_c24_se0.25', 'ir_r1_k3_s1_e4_c24_se0.25',
       'ir_r1_k3_s1_e4_c24_se0.25'],
      # stage 2, 56x56 in
      ['ir_r1_k5_s2_e4_c40_se0.25', 'ir_r1_k5_s1_e4_c40_se0.25', 'ir_r1_k5_s2_e4_c40_se0.25',
       'ir_r1_k5_s2_e4_c40_se0.25'],
      # stage 3, 28x28 in
      ['ir_r1_k3_s2_e6_c80_se0.25', 'ir_r1_k3_s1_e4_c80_se0.25', 'ir_r1_k3_s1_e4_c80_se0.25',
       'ir_r2_k3_s1_e4_c80_se0.25'],
      # stage 4, 14x14in
      ['ir_r1_k3_s1_e6_c96_se0.25', 'ir_r1_k3_s1_e6_c96_se0.25', 'ir_r1_k3_s1_e6_c96_se0.25',
       'ir_r1_k3_s1_e6_c96_se0.25'],
      # stage 5, 14x14in
      ['ir_r1_k5_s2_e6_c192_se0.25', 'ir_r1_k5_s1_e6_c192_se0.25', 'ir_r1_k5_s2_e6_c192_se0.25',
       'ir_r1_k5_s2_e6_c192_se0.25'],
      # stage 6, 7x7 in
      ['cn_r1_k1_s1_c320_se0.25'],
  ]
```

There are specific numbers of blocks for each stage. In this case, there are 4,4,5,4,4 blocks. 

However, in your paper, the repeat number is ranging from 4 to 6. The code doesn't match the description in the paper. 

![image](https://user-images.githubusercontent.com/29230784/166862230-15802760-e1ab-4b58-9e8e-847e4d2ebe43.png)

**Question 2:**

Another question is about skip connection operation. In your paper, the description is as below:

![image](https://user-images.githubusercontent.com/29230784/166862394-19a4119c-65f8-491b-8f4c-9fd0b2b4f8e1.png)

But I can not find the Skip Connection in your search space. 

https://github.com/microsoft/Cream/blob/bd49e0b933eeb60147f2b3bcecf241f06d92b435/Cream/lib/models/builders/build_supernet.py#L34

There are only 6 operations in your Search Space.

**Comment by Z7zuqer** [comment]
Hi,

Thanks for your interest in our project!

Both Q1 and Q2 can refer to [this line](https://github.com/microsoft/Cream/blob/bd49e0b933eeb60147f2b3bcecf241f06d92b435/Cream/lib/models/structures/supernet.py#L185) that we perform search space searching before the supernet training. 

Best,
Hao.

**Comment by pprp** [comment]
Thank you for your reply! 

Can you explain the meaning of order and limit?

https://github.com/microsoft/Cream/blob/bd49e0b933/Cream/lib/utils/search_structure_supernet.py#L8-L9

Also, I haven't figured out the second question. Do you mean to determine skip connection by the `search_for_layer` function? 

For example, if the block number of stage 2 is 2,  does that mean we picked 4 skip connection operations?

**Comment by Z7zuqer** [comment]
Hi,

1) "order" indicates how to shrink the search space in terms of 5 stages. "Limit" indicates the maximum layers which can be reduced by the current shrinking step. We empirically find shallow layers contribute less to the network performance than deep layers.

2) Yes, we implement the skip connection by directly skipping the layer before the supernet training. To compare with, some other methods (i.e., OFA) skip layers during supernet training.

3) Yes, it indicates we skip 4 layers in stage 2.

Best,
Hao.

**Comment by pprp** [comment]
Thank you for your kind reply!
