### ISSUE TITLE
I want to know how Mini-swin can be transplanted to other networks as a backbone

### ISSUE THREAD

**Issue by LUO77123** [microsoft/Cream#91]
When I look at swin_transformer.py and swin_transformer_distill.py, I find that distillation code is added, but how to call it is in the main.py file, so I don't quite understand how to put Mini-swin as a backbone into other networks. Can you guide me? Thanks

**Comment by wkcn** [comment]
@LUO77123 
Thanks for your attention to our work!

In fact, the code named [`swin_transformer_minivit_distill.py`](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit_distill.py) only has the extra intermediate outputs for the distillation, comparing with the one [`swin_transformer_minivit.py`](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit.py).

If you want to put Mini-Swin as a backbone into other codebase, you can create an instance [`SwinTransformerMiniViT`](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit.py#L585) by [the code](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/build.py#L28) with the same arguments as `SwinTransformerMiniViTDistill`, except of the extra arugments `is_student` and `fit_size_C`.

**Comment by LUO77123** [comment]
> @LUO77123 Thanks for your attention to our work!
> 
> In fact, the code named [`swin_transformer_minivit_distill.py`](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit_distill.py) only has the extra intermediate outputs for the distillation, comparing with the one [`swin_transformer_minivit.py`](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit.py).
> 
> If you want to put Mini-Swin as a backbone into other codebase, you can create an instance [`SwinTransformerMiniViT`](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit.py#L585) by [the code](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/build.py#L28) with the same arguments as `SwinTransformerMiniViTDistill`, except of the extra arugments `is_student` and `fit_size_C`.

Thank you for replying to my questions in your busy schedule. I'll try in the direction you gave me. If there's anything you don't understand, I'll bother you again.Thanks!

**Comment by wkcn** [comment]
Close the issue.
Feel free to reopen it if you meet some problem : )
