### ISSUE TITLE
About MiniViT

### ISSUE THREAD

**Issue by DOHA-HWANG** [microsoft/Cream#92]
Dear Authors,

I read your paper and reviewed your codes. Thanks for sharing valuable things.
About this, I have some questions.
1. Flops
    As far as I understood, I suppose that MiniViT reduced memory by weight sharing, but the number of flops is bigger than ViT because of adding transform blocks and others. If you don't mind, please share your opinions.
2. The number of transformer encoder blocks
    It is a bit similar to the above question. In your paper's fig.2, when you share the weight between two layers, it looks like reducing the layer by half. Do the two layers with the same weight memories still exist, or will two layers reduce by one layer?

Thanks in advance.

Doha

**Comment by wkcn** [comment]
@DOHA-HWANG 
Thanks for your attention to our work!

1. FLOPs
Yes. In MiniViT, the number of parameters is reduced significantly, however the FLOPs is slightly larger than the original one. We also try to reduce the number of blocks, e.g., reduce the number of blocks from 12 to 11 for Mini-DeiT-Tiny (the first 10 blocks share 5 weights, and the last block has one weight), it achieves 72.3% Top-1 accuracy on ImageNet-1k val.

Welcome to improve it  : )

2. The number of transformer encoder blocks
The number of transformer encoder blocks are not changed. Every-two blocks share the same weight, except of layer norm and the weight transformation.

**Comment by DOHA-HWANG** [comment]
Dear wkcn,
Thanks for your kind answer :)
