### ISSUE TITLE
How use the minivit to object detection ? Need how to change code ?

### ISSUE THREAD

**Issue by funny000** [microsoft/Cream#93]
hi, authors, the minivit is a very good job. So i try use it to my job about object detection, And have a question how to change the code,  

I change the head layer of minivit to detection layer, only use minivit to learning the image feature, and gives the ground truth object 

coordinates, for example xmin,ymin,xmax,ymax; So can you achieve object detection by doing this ?
Thanks.

**Comment by wkcn** [comment]
Close it. Feel free to reopen it if any problem exists : )
