### ISSUE TITLE
How to get the Flops of AutoFormer ?

### ISSUE THREAD

**Issue by shadowpa0327** [microsoft/Cream#94]
Hi, first thanks for the nice work! It's really interesting, 

Currently, I did like to calculate the flops of AutoFormer subnet, however, when I use `flops_count` in fvcore.nn  that you suggest in other issue, I could not get the proper result.

Is there any other way to get the calculation of the Flops?

Best regard

**Comment by nbl97** [comment]
Hi, thanks for your interest in our work. We write a function called [get_complexity](https://github.com/microsoft/Cream/blob/43514f073c64b804685aa9b3671ad77ef12b513d/AutoFormer/model/supernet_transformer.py#L295) to calculate the Flops. After you have set the subnet, you can use this function to get the Flops of the subnet.
