### ISSUE TITLE
Question about DeiT-with-iRPE

### ISSUE THREAD

**Issue by zjm1640160263** [microsoft/Cream#98]
I try the code DeiT-with-iRPE.
In code ,which point you select as the reference positions ,the top-left position(0,0)or the thecenter position(7,7)?

**Comment by wkcn** [comment]
Hi @zjm1640160263, Thanks for your attention to our work.

There are multiple reference positions. For example, when computing the relative positions between queries and keys in DeiT, there are `14x14` reference positions. All positions of keys are the reference positions to the positions fo queries.

We compute all relative positions in the following code.
https://github.com/microsoft/Cream/blob/main/iRPE/DeiT-with-iRPE/irpe.py#L342
 ```python
        pos1 = pos.view((max_L, 1, 2))
        pos2 = pos.view((1, max_L, 2))
        # diff: shape of (L, L, 2) 
        diff = pos1 - pos2
```

`pos1` denotes the absolute positions of queries, with the shape of (14x14, 1, 2), namely 14x14 x-y coordinates of queries in DeiT with the resolution of 224x224.
`pos2` denotes the absolute positions of keys, with the shape of (1, 14x14, 2), where `14x14` keys' positions are the reference positions to the queries.
`diff` denotes `(14x14) x (14x14)` relative positions between queries and keys, whose shape is (14x14, 14x14, 2)
